[connections.supabase]
url = "https://ahbsoacmxuokcbdhafqt.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoYnNvYWNteHVva2NiZGhhZnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjczMDcsImV4cCI6MjA2OTI0MzMwN30.rvHOIc6TdJ3G0T84Rl9CDiVR_qud7E11xk45QEClhiY"